### ISSUE TITLE
Net_demo_installer script does not work with -r option

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/demo#104]
error log : 

TASK [include_vars] ************************************************************
ok: [node1] => (item=contiv_network)
ok: [node2] => (item=contiv_network)
ok: [node3] => (item=contiv_network)
ok: [node2] => (item=contiv_storage)
ok: [node1] => (item=contiv_storage)
ok: [node2] => (item=swarm)
ok: [node1] => (item=swarm)
ok: [node3] => (item=contiv_storage)
ok: [node2] => (item=ucp)
ok: [node1] => (item=ucp)
ok: [node3] => (item=swarm)
ok: [node1] => (item=docker)
ok: [node2] => (item=docker)
ok: [node3] => (item=ucp)
ok: [node1] => (item=etcd)
ok: [node3] => (item=docker)
ok: [node2] => (item=etcd)
ok: [node3] => (item=etcd)

TASK [include] *****************************************************************
included: /home/admin/ansible/roles/ucarp/tasks/cleanup.yml for node1, node2, node3
fatal: [node1]: FAILED! => {"failed": true, "reason": "'item' is undefined"}
...ignoring
fatal: [node2]: FAILED! => {"failed": true, "reason": "'item' is undefined"}
...ignoring
fatal: [node3]: FAILED! => {"failed": true, "reason": "'item' is undefined"}
...ignoring
included: /home/admin/ansible/roles/contiv_storage/tasks/cleanup.yml for node1, node2, node3
included: /home/admin/ansible/roles/swarm/tasks/cleanup.yml for node1, node2, node3
included: /home/admin/ansible/roles/ucp/tasks/cleanup.yml for node1, node2, node3
included: /home/admin/ansible/roles/etcd/tasks/cleanup.yml for node1, node2, node3
included: /home/admin/ansible/roles/nfs/tasks/cleanup.yml for node1, node2, node3
included: /home/admin/ansible/roles/docker/tasks/cleanup.yml for node1, node2, node3

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @./ansible/cleanup.retry

PLAY RECAP *********************************************************************
node1                      : ok=9    changed=0    unreachable=0    failed=1  
node2                      : ok=9    changed=0    unreachable=0    failed=1  
node3                      : ok=9    changed=0    unreachable=0    failed=1

**Comment by gaurav-dalvi** [comment]
This should run for all combinations below.
Test cases :
1: ./net_demo_installer -ar
2: ./net_demo_installer -ars
3: ./net_demo_installer -r
4: ./net_demo_installer -rs 
5: ./net_demo_installer -a
6: ./net_demo_installer

**Comment by gaurav-dalvi** [comment]
@apoorva11029 : Looks like with your last fix (-s option this is broken.) Could you please take care of this one ?

**Comment by apoorva11029** [comment]
-r option isn't working for the older version also. Doesn't seem like the -s(silent) option issue.

**Comment by gaurav-dalvi** [comment]
Closed with PR #105
