### ISSUE TITLE
net_demo_installer script is not able to take custom aci-gw version

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/demo#128]
As mentioned here : https://github.com/contiv/demo/tree/master/net#step-3-provide-executable-privileges-and-run-installer-script

export aci_gw_image="contiv/aci-gw:v2"

sometimes works and sometime it does not work.

**Comment by rhim** [comment]
Can you attach logs of a failure run?

**Comment by gaurav-dalvi** [comment]
Might be related to https://github.com/contiv/demo/issues/126
