### ISSUE TITLE
Result of parsed yaml out of order

### ISSUE THREAD

**Issue by acusworth** [contiv/demo#13]
The result of the parsed yaml file always puts the numerically higher IP address as node 1 instead of the following the order set in the yaml file. For example if the yaml file has ips configured at 74 and 78 as node 1 and 2 respectively the parsed result ends up being 78 and 74 as node 1 and 2 respectively.

**Comment by dvavili** [comment]
@acusworth: This is generally not an issue with respect to the setting up or functionality. The only effect this has is to have netmaster run on the first node. Having said that, we will work on this as an enhancement to have predictability in knowing where the master node is.

**Comment by gaurav-dalvi** [comment]
@shaleman  with netmaster runs now as HA on all the nodes in cluster, Do we still need to consider this as Issue ?

**Comment by shaleman** [comment]
@gaurav-dalvi: Yes, we can probably close this issue since netmaster can run on multiple nodes now. But, ansible added support for master and worker roles. We should make use of those roles in net_demo_installer
