### ISSUE TITLE
net_demo_installer is failing after ansible playbook execution has finished !

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/demo#134]
TASK [contiv_network : set fwd mode] *******************************************
changed: [node1]

PLAY RECAP *********************************************************************
node1                      : ok=62   changed=32   unreachable=0    failed=0   
node2                      : ok=60   changed=30   unreachable=0    failed=0   

Using default tag: latest
Warning: failed to get default registry endpoint from daemon (Cannot connect to the Docker daemon. Is the docker daemon running on this host?). Using system default: https://index.docker.io/v1/
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

Centos 7,
Latest netplugin
ACI mode.

**Comment by dvavili** [comment]
This issue needs to be raised against ansible repository.

**Comment by gaurav-dalvi** [comment]
Not seeing this issue now. Closing it.
