### ISSUE TITLE
Errors when not allowing Passwordless Sudo access

### ISSUE THREAD

**Issue by mpduarte** [contiv/demo#32]
- Install failed because it couldn’t run: "apt-get install python-apt -y -q --force-yes” on half the nodes.
- Contiv Standalone Install: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: ERROR! 'dict object' has no attribute u'ansible_enp4s0f0'"} on all hosts

**Both issues were resolved once I went ahead and implemented in passwordless sudo.**

**Comment by mpduarte** [comment]
updating title to better describe the part of demo that's having the issue.

**Comment by gaurav-dalvi** [comment]
@shaleman  : I think we can close this issue now.

**Comment by shaleman** [comment]
Closing this issue since it went away with password-less sudo
