### ISSUE TITLE
net_demo_installer script installs ansible 1.9.4 version on centos 7.x. Setup needs ansible 2.0.x

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/demo#56]
with Centos 7.x version , steps mentioned in the net_demo_installer script, installs ansible 1.9.4 version. Because of which this setup does not succeed. Need to install ansible 2.0.x using pip.

Current Steps to install ansible : 
if  [[ ${OS_TYPE} =~ ^CentOS ]]; then
    sudoExec yum install -y epel-release epel-testing git wget
    sudoExec yum install -y ansible
    docker_version="1.10.3"
fi

**Comment by gaurav-dalvi** [comment]
This should install anisble 2.0.x on centos.

if [[ ${OS_TYPE} =~ ^CentOS ]]; then
sudoExec easy_install pip
sudoExec pip install ansible
docker_version="1.10.3"
fi

**Comment by mapuri** [comment]
using pip along side yum is a bad idea as it messes up yum package database.

We already install ansible using epel-testing repo elsewhere so current logic should have worked, maybe we just need to specify the version explicitly like `sudoExec yum install -y ansible-2*` ?
