### ISSUE TITLE
Post Install Rules not Applying to Traffic

### ISSUE THREAD

**Issue by acusworth** [contiv/demo#7]
After a successful install and running netctl to create policy, rules and group. Traffic is not being affected by the rules as expected. 
So after running the instructions from docks.contiv.io to try and reproduce the same effect blocking the traffic. It hasn’t been successful as all traffic is passing as normal and ignoring any applied rule.
I believe contiv might have an issue or the instructions have changed for setting up rules.

**Comment by dvavili** [comment]
@acusworth: Are you still facing this issue? If you are seeing the policy, rules and groups getting creating properly, it is ideally a netplugin issue and it's better to open the issue against the netplugin repository to track it efficiently. If you are unsure of whether it's an installer/netplugin issue, I can help you in figuring this out.

**Comment by acusworth** [comment]
@DivyaVavili This was the issue @jainvipin and I worked on. Found it was ansible and logged issue there.
