### ISSUE TITLE
k8sdemo: aci mode not setup properly

### ISSUE THREAD

**Issue by pkeerthana** [contiv/demo#79]
By default, contrib scripts assume aci mode of operation for k8scluster. But do not setup netplugin in aci fabric mode. 
[admin@k8master pods]$ netctl global info
Fabric mode: default <-- not aci in aci-fabric-mode
Vlan Range: 1-4094
Vxlan range: 1-10000

**Comment by jojimt** [comment]
_By default, contrib scripts assume aci mode of operation for k8scluster._
Actually, there is no such assumption. The cluster itself does not care whether it is aci mode or not. The correct mode has to be configured via CLI. For an example, see scripts in samples.

**Comment by gaurav-dalvi** [comment]
@jojimt Can we close this issue ?
