### ISSUE TITLE
docker installation is failing

### ISSUE THREAD

**Issue by ankithg** [contiv/demo#82]
I had run the script and everything was up. My VMs shut down for some reason. Once I brought them up, docker swarm and netmaster were down. I tried running the script again. I am consistently running into this error

TASK [docker : ensure docker is started] ***************************************
fatal: [node1]: FAILED! => {"changed": false, "failed": true, "msg": "Job for docker.service failed because the control process exited with error code. See \"systemctl status docker.service\" and \"journalctl -xe\" for details.\n"}

**Comment by ankithg** [comment]
**rm -rf /var/lib/docker/**  solved the problem

**Comment by jainvipin** [comment]
@shaleman - is this a docker issue, or our installation issue?

**Comment by shaleman** [comment]
This sounds like its related to `overlayfs`. I'm guessing, different version of docker was previously installed on this machine which was using default graph-driver. In our ansible, we force `overlayfs` graph driver. Docker daemon will fail to start if there are docker images in /var/lib/docker from different graph driver. @mapuri @vvb Should we force remove /var/lib/docker/ before installing docker in ansible?
