### ISSUE TITLE
script installation is faling 

### ISSUE THREAD

**Issue by ankithg** [contiv/demo#83]
I am running the script on Ubuntu 15.10

TASK [base : upgrade system (debian)] ******************************************
ok: [node1]
fatal: [node3]: FAILED! => {"changed": false, "failed": true, "msg": "Could not fetch updated apt files"}
fatal: [node2]: FAILED! => {"changed": false, "failed": true, "msg": "Could not fetch updated apt files"}

**Comment by ankithg** [comment]
rm -rf /var/lib/apt/lists/\*  on the failed nodes solved the problem

**Comment by gaurav-dalvi** [comment]
@ankithg : Could you please close the issue if you dont see this problem ?
