### ISSUE TITLE
swarm client and server version mismatch

### ISSUE THREAD

**Issue by ankithg** [contiv/demo#84]
This causes issue while running docker-py

admin06-18:~$ sudo docker -H :2375 version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.2
 Git commit:   a34a1d5
 Built:        Fri Nov 20 13:20:08 UTC 2015
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.2.0
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   a6c1f14
 Built:        Wed Apr 13 05:58:31 UTC 2016
 OS/Arch:      linux/amd64
admin@06-18:~$

**Comment by gaurav-dalvi** [comment]
which demo you are running ?
Swarm or K8s ?

**Comment by dawelsch** [comment]
k8s.

Is there more than one demo? You sent me two setups:

 https://github.com/contiv/demo/blob/master/k8s/README.md

 https://github.com/contiv/netplugin/tree/master/mgmtfn/k8splugin#example-1-no-network-labels--pod-placed-in-default-network

What's the difference? The second one seems to be an extended exercise with a different set of scripts.

Dave

## 

Dave Welsch
Senior Technical Writer
Product Development
dawelsch@cisco.com

**Comment by jainvipin** [comment]
The first one is to run on standard VMs or Baremetal nodes. The second one is to try this out in a demo environment on a MAC or linux server I.e. The second one brings up vagrant setup, the first one doesn't spin up VMs, etc.

Thanks,
-Vipin

**Comment by gaurav-dalvi** [comment]
@ankithg : I have upgraded contiv versions. Could you please clean everything and try running net_demo_installer script again ?

**Comment by ankithg** [comment]
It doesn't work

Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:38:55 2016
 OS/Arch:      linux/amd64

Server:
 Version:      swarm/1.2.0
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   a6c1f14
 Built:        Wed Apr 13 05:58:31 UTC 2016
 OS/Arch:      linux/amd64

**Comment by gaurav-dalvi** [comment]
Can you please check Version mentioned here :
https://github.com/contiv/demo/blob/master/net/net_demo_installer#L148

It should have this :

contiv_network_version="v0.1-05-19-2016.08-34-56.UTC"
docker_version="1.11.1"

Also please clear out all etcd states before you make fresh start:
etcdctl rm --recursive /contiv.io
etcdctl rm --recursive /docker
etcdctl rm --recursive /skydns
Then you can restart all the nodes and then start again.

**Comment by ankithg** [comment]
How do i check contiv version

**Comment by gaurav-dalvi** [comment]
you can check netctl version.
Make sure you have 5/19 version on net_demo_installer script.

**Comment by ankithg** [comment]
netctl version 
Version: v0.1-05-19-2016.08-34-56.UTC
GitCommit: 6efd1ef
BuildTime: 05-19-2016.08-34-56.UTC

**Comment by gaurav-dalvi** [comment]
You should get something like this :

netctl version
Client Version:
Version: pv0.1-06-07-2016.18-33-08.UTC
GitCommit: b4739c8-unsupported
BuildTime: 06-07-2016.18-33-08.UTC

Server Version:
Version: pv0.1-06-07-2016.18-33-08.UTC
GitCommit: b4739c8-unsupported
BuildTime: 06-07-2016.18-33-08.UTC

**Comment by gaurav-dalvi** [comment]
Let us know when you run net_demo_installer script again after updating the version i told you.

**Comment by gaurav-dalvi** [comment]
@dawelsch : Gentle reminder !

**Comment by gaurav-dalvi** [comment]
@ankithg : Could you please verify this again ?
