### ISSUE TITLE
net_demo_installer fails due to later OVS version

### ISSUE THREAD

**Issue by hbasappa** [contiv/demo#86]
I am not sure how a later version of OVS got installed on one of the nodes. But even after running net_demo_installer -c/net_demo_installer -r it does not work.

Logs:
TASK [contiv_network : install ovs-common (debian)] ****************************
fatal: [node1]: FAILED! => {"changed": false, "failed": true, "msg": "A later version is already installed"}

admin04@monit-04-176:~$ sudo ovs-ofctl  --version
ovs-ofctl (Open vSwitch) 2.4.0
Compiled Oct 16 2015 09:22:33
OpenFlow versions 0x1:0x4

Working nodes:

admin04@monit-04-175:~$ sudo ovs-ofctl  --version
ovs-ofctl (Open vSwitch) 2.3.1
Compiled Jun 12 2015 00:09:03
OpenFlow versions 0x1:0x4

**Comment by hbasappa** [comment]
doing  sudo apt-get remove openvswitch-common and re-running the script solves it.

**Comment by kiranneo** [comment]
Hi. Is there a way to by pass this Version Check? Why should the Ansible script bail out when there is a later version installed? Please help us by pass this if possible.

**Comment by gaurav-dalvi** [comment]
@mapuri : Could you please comment on this one ?

**Comment by ramukima** [comment]
The following let me proceed -

```
apt-get purge openvswitch-switch (if already installed)
mkdir -p /tmp/ovs
mv /usr/bin/ovs* /tmp/ovs/
mv /usr/sbin/ovs* /tmp/ovs/
apt-get install /tmp/ovs-common.deb -y
apt-get install /tmp/ovs-switch.deb -y
```

and re-run net_demo_installer.

**Comment by rhim** [comment]
Thanks @ramukima for cleanup steps.
