### ISSUE TITLE
Take contiv_version as Environment variable rather than hard coding in net_demo_installer script and k8s script.

### ISSUE THREAD

**Issue by gaurav-dalvi** [contiv/demo#90]
Please modify the net_demo_installer script and k8s setup script to take contiv_network_version through command line / environment variable. Right we hard code version string in out scripts which is not ideal way to do it.

**Comment by reshmagiliyal** [comment]
Issue solved.  net_demo_installer and k8s setup scripts are modified to take contiv network version through environment variable. Readme files are modified explaining the steps accordingly.

**Comment by gaurav-dalvi** [comment]
@reshmagiliyal : Thanks a lot !

**Comment by gaurav-dalvi** [comment]
Fixed with this : https://github.com/contiv/demo/pull/94
